apiVersion: v1
kind: ConfigMap
metadata:
  name: autorepair-config
  namespace: autorepair
  labels:
    app: autorepair
data:
  PORT: "8080"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "autorepair"
  DB_USER: "postgres"
  DB_SSLMODE: "disable"
