apiVersion: v1
kind: Service
metadata:
  name: autorepair-service
  namespace: autorepair
  labels:
    app: autorepair
    component: api
spec:
  type: ClusterIP
  selector:
    app: autorepair
    component: api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
